CREATE TABLE IF NOT EXISTS "user" (id TEXT PRIMARY KEY, name TEXT NOT NULL, email TEXT NOT NULL UNIQUE, emailVerified INTEGER NOT NULL DEFAULT 0, image TEXT, createdAt INTEGER NOT NULL, updatedAt INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS session (id TEXT PRIMARY KEY, expiresAt INTEGER NOT NULL, token TEXT NOT NULL UNIQUE, createdAt INTEGER NOT NULL, updatedAt INTEGER NOT NULL, ipAddress TEXT, userAgent TEXT, userId TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE);
CREATE INDEX IF NOT EXISTS session_user ON session(userId);
CREATE TABLE IF NOT EXISTS account (id TEXT PRIMARY KEY, accountId TEXT NOT NULL, providerId TEXT NOT NULL, userId TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE, accessToken TEXT, refreshToken TEXT, idToken TEXT, accessTokenExpiresAt INTEGER, refreshTokenExpiresAt INTEGER, scope TEXT, password TEXT, createdAt INTEGER NOT NULL, updatedAt INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS account_user ON account(userId);
CREATE TABLE IF NOT EXISTS verification (id TEXT PRIMARY KEY, identifier TEXT NOT NULL, value TEXT NOT NULL, expiresAt INTEGER NOT NULL, createdAt INTEGER, updatedAt INTEGER);
CREATE TABLE branes (id TEXT PRIMARY KEY, owner_id TEXT NOT NULL REFERENCES "user"(id), title TEXT NOT NULL, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL);
CREATE INDEX branes_owner ON branes(owner_id, updated_at);
CREATE TABLE blocks (id TEXT PRIMARY KEY, owner_id TEXT NOT NULL REFERENCES "user"(id), kind TEXT NOT NULL CHECK(kind IN ('text','image','webpage','response')), created_at INTEGER NOT NULL);
CREATE TABLE block_live_state (block_id TEXT PRIMARY KEY REFERENCES blocks(id), content_json TEXT NOT NULL CHECK(json_valid(content_json)), version INTEGER NOT NULL DEFAULT 0, updated_at INTEGER NOT NULL);
CREATE TABLE block_revisions (id TEXT PRIMARY KEY, block_id TEXT NOT NULL REFERENCES blocks(id), content_json TEXT NOT NULL CHECK(json_valid(content_json)), created_at INTEGER NOT NULL);
CREATE INDEX revisions_block ON block_revisions(block_id, created_at);
CREATE TRIGGER immutable_revision_update BEFORE UPDATE ON block_revisions BEGIN SELECT RAISE(ABORT, 'immutable revision'); END;
CREATE TRIGGER immutable_revision_delete BEFORE DELETE ON block_revisions BEGIN SELECT RAISE(ABORT, 'immutable revision'); END;
CREATE TABLE placements (id TEXT PRIMARY KEY, brane_id TEXT NOT NULL REFERENCES branes(id), block_id TEXT NOT NULL REFERENCES blocks(id), x REAL NOT NULL, y REAL NOT NULL, width REAL NOT NULL CHECK(width>=180), height REAL NOT NULL CHECK(height>=120), z_index INTEGER NOT NULL DEFAULT 0, updated_at INTEGER NOT NULL);
CREATE INDEX placements_brane ON placements(brane_id);
CREATE INDEX placements_block ON placements(block_id);
CREATE TABLE assets (id TEXT PRIMARY KEY, owner_id TEXT NOT NULL REFERENCES "user"(id), storage_key TEXT NOT NULL UNIQUE, mime TEXT NOT NULL, size INTEGER NOT NULL, created_at INTEGER NOT NULL);
CREATE TABLE conversations (id TEXT PRIMARY KEY, owner_id TEXT NOT NULL REFERENCES "user"(id), created_at INTEGER NOT NULL);
CREATE TABLE conversation_messages (id TEXT PRIMARY KEY, conversation_id TEXT NOT NULL REFERENCES conversations(id), parent_id TEXT REFERENCES conversation_messages(id), role TEXT NOT NULL CHECK(role IN ('user','assistant')), revision_id TEXT NOT NULL REFERENCES block_revisions(id), created_at INTEGER NOT NULL, context_json TEXT NOT NULL DEFAULT '[]');
CREATE INDEX messages_conversation ON conversation_messages(conversation_id);
CREATE TRIGGER immutable_message_update BEFORE UPDATE ON conversation_messages BEGIN SELECT RAISE(ABORT, 'immutable message'); END;
CREATE TABLE runs (id TEXT PRIMARY KEY, owner_id TEXT NOT NULL REFERENCES "user"(id), brane_id TEXT NOT NULL REFERENCES branes(id), submission_key TEXT NOT NULL, request_hash TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN ('queued','claimed','running','completed','failed','cancel_requested','cancelled','interrupted')), provider TEXT NOT NULL, model TEXT NOT NULL, options_json TEXT NOT NULL, output_block_id TEXT NOT NULL REFERENCES blocks(id), conversation_id TEXT NOT NULL REFERENCES conversations(id), continue_from TEXT REFERENCES conversation_messages(id), retry_of TEXT REFERENCES runs(id), lease_owner TEXT, lease_until INTEGER, usage_json TEXT, estimated_usage_json TEXT, error TEXT, created_at INTEGER NOT NULL, started_at INTEGER, finished_at INTEGER, UNIQUE(owner_id,submission_key));
CREATE INDEX runs_queue ON runs(status,created_at);
CREATE INDEX runs_brane ON runs(brane_id,created_at);
CREATE INDEX runs_owner ON runs(owner_id,status);
CREATE TRIGGER frozen_run_request BEFORE UPDATE OF owner_id, brane_id, submission_key, request_hash, provider, model, options_json, output_block_id, conversation_id, continue_from, retry_of ON runs BEGIN SELECT RAISE(ABORT, 'immutable run request'); END;
CREATE TABLE run_inputs (run_id TEXT NOT NULL REFERENCES runs(id), position INTEGER NOT NULL, kind TEXT NOT NULL CHECK(kind IN ('reference','lineage_reference','lineage','prompt')), label TEXT NOT NULL, role TEXT NOT NULL CHECK(role IN ('user','assistant')), revision_id TEXT NOT NULL REFERENCES block_revisions(id), PRIMARY KEY(run_id,position));
CREATE TRIGGER immutable_input_update BEFORE UPDATE ON run_inputs BEGIN SELECT RAISE(ABORT, 'immutable run input'); END;
CREATE TRIGGER immutable_input_delete BEFORE DELETE ON run_inputs BEGIN SELECT RAISE(ABORT, 'immutable run input'); END;
CREATE TABLE run_outputs (run_id TEXT PRIMARY KEY REFERENCES runs(id), revision_id TEXT NOT NULL REFERENCES block_revisions(id), message_id TEXT NOT NULL REFERENCES conversation_messages(id));
CREATE TRIGGER immutable_output_update BEFORE UPDATE ON run_outputs BEGIN SELECT RAISE(ABORT, 'immutable output'); END;
CREATE TABLE run_checkpoints (run_id TEXT PRIMARY KEY REFERENCES runs(id), text TEXT NOT NULL, updated_at INTEGER NOT NULL);
CREATE TABLE run_attempts (id TEXT PRIMARY KEY, run_id TEXT NOT NULL REFERENCES runs(id), worker_id TEXT NOT NULL, started_at INTEGER NOT NULL, heartbeat_at INTEGER NOT NULL, finished_at INTEGER, outcome TEXT);
CREATE TABLE ingestions (block_id TEXT PRIMARY KEY REFERENCES blocks(id), status TEXT NOT NULL, error TEXT, created_at INTEGER NOT NULL);

CREATE TRIGGER immutable_message_delete BEFORE DELETE ON conversation_messages BEGIN SELECT RAISE(ABORT, 'immutable message'); END;
CREATE TRIGGER immutable_output_delete BEFORE DELETE ON run_outputs BEGIN SELECT RAISE(ABORT, 'immutable output'); END;
